language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devops1lab
  api_key:
    secure: CZewYFZUKEiWFrmnv+nplEagCWr9Xwp2/aFfdw57L9W7gIoRJeizI4P/d5lCF+9AbIZ+o+aJ/oIm4ggGyO6D1FzmZsxGnvPoA0LUHxtaTBRXBmA8EFmnzwFtT04+HvvTMKTV+aLeuM2i8zbKRpcHyQYAR9Ct9DgdXbw4wVHcf49GeSbYGH8LPnw4arP4+fdKAzfMD97HzhhbxWNRSGAM4vXO86NN3gXSBsip9QGPIIOaymjMMTM049LIFk3J6841X7iS9BUDRfpftO9JP5fb0fcaqcRT433n0eaDcv9rYQGD+2CrLBldSmN6sn3lR8o3k79YMM+n0O7bnkTaCY2VL6s4qCpIEuAM9HnBJpbElo2OpLdIAT+Lg2EI721g5arGpVGbkG9NFA1O1jYxWbJ9GFlK2OPkjqGY/4KwDD1mfYQpCsyfo+JX8S9YHd3LJQ61U0Ngk8oqMNNheXiWHsYEoVC4f6Ynkozp/7QEHOjKsw5/TB3LEyWZ8xmGGwm5+b6FWjp5dI4Y6PwsyHEs7nzxUFps3xQiZXFzNrSYHC6uNQxnoUK6yEXAkKS2SxRv8rRIrTgrHZCJgaYQSp6mxriUdNdPO+E2BroL1L0oAzfBRPYHf/jA3pyq5bck/LFwKepD2XJfaCD4SqN2ILMkVn/pHTbYz9WX+UBI2n2XeozVHkA=
